### ISSUE TITLE
Error: watch imgin/ ENOENT

### ISSUE THREAD

**Issue by edgarscr** [Advill/Swift-Hack-a-thon#1]
Hello i am getting this error and i dont understand why can u help me to fix?

![image](https://user-images.githubusercontent.com/33737821/54039513-1c28a580-4191-11e9-8ebd-3291d8353798.png)

**Comment by Advill** [comment]
Hey! It looks like the fs module is either not loaded or not loading
properly. Have you installed all dependencies using `npm install' in the
root directory of the project?

**Comment by edgarscr** [comment]
look the image 

![image](https://user-images.githubusercontent.com/33737821/54043713-45e6ca00-419b-11e9-8e6f-ff5e0bd23c01.png)

**Comment by Advill** [comment]
Yes, the optional dependencies should not be a problem, and I am aware of
the vulnerabilities but have not taken the time to fix them as the program
does not access the external Internet anyways. You are welcome to fix them
with npm, and the program should still work fine

**Comment by edgarscr** [comment]
can you help me what i have to do?

**Comment by Advill** [comment]
You should be good to go where you are, just keep following the
instructions on the readme. I'm out at the moment so I likely won't be able
to help any more for a few hours but you have everything installed for it
to work.

**Comment by edgarscr** [comment]
Yes, i go to read again and try in case same problem i go to write you. thanks for ur answer

**Comment by edgarscr** [comment]
look this http://85.214.102.103:8080/

i dont get response of the values of images in imgin

![image](https://user-images.githubusercontent.com/33737821/54047895-4d5fa080-41a6-11e9-99a6-df9b3f1ea60f.png)


and this error in server.js

![image](https://user-images.githubusercontent.com/33737821/54047972-797b2180-41a6-11e9-9a7e-defcd8f6f56f.png)


otherserver.js

![image](https://user-images.githubusercontent.com/33737821/54049040-6d449380-41a9-11e9-8931-02680fa6a6e3.png)

**Comment by edgarscr** [comment]
the system read license from photos?

**Comment by edgarscr** [comment]
because i fixed all bugs but the system dont say nothing 

![image](https://user-images.githubusercontent.com/33737821/54056963-9a9c3c00-41bf-11e9-9e4a-fc892b1f8a9b.png)

**Comment by Advill** [comment]
So I'm not sure what the problem could be, I'm having trouble getting this to run myself now that I'm on an arch system instead of a Debian one. The fact that the filewatcher isn't giving any output at all is strange, because even without openalpr installed on my machine the file is detected, as that should just be `fs` finding files. I wouldn't recommend wasting too much time getting this to work, as it was put together quickly and dirtily, and was buggy when we finished. If you are truly interested in something like this it would be much better to start over fresh with a new project. Some friends and I are intending to do this very thing over the summer, but have yet to have time to do so.

Either way, I don't think I can offer much more help on this project, as I never really intended to fix any of the problems, and keep it on github mostly for reference.

**Comment by edgarscr** [comment]
this is my current bug idk why

![image](https://user-images.githubusercontent.com/33737821/54091826-c4d23300-4352-11e9-8947-deb5a88e7d0e.png)

**Comment by Advill** [comment]
This looks like an error on alpr/tesseract's end. Mine worked as soon as i had everything installed so I can't help with this bug
